### PR TITLE
Add m1 support

### PR DESCRIPTION
**Pull request by hyp3rflow**
Release universal lib for macOS (aarch64 + x86_64 both)

If you think there is a much simpler approach on workflow, feel free to comment. (I'm not good at writing workflow :q)
Also you can see the working example on: https://github.com/hyp3rflow/deno_installer/releases/tag/0.0.3-test

### CODE REVIEW

**Comment by marc2332** [comment]
LGTM. Maybe when https://github.com/rust-lang/cargo/issues/8875 gets fixed, this can be simplified. 
I don't own a M1, have you actually tried and worked fine (silly question I know)? 😁 

_This reminds me I should add some tests_

**Comment by hyp3rflow** [comment]
@marc2332 yes, I tried it on my m1 machine and I think it works fine because I can get `.dmg` file after building `example/oak` in this repo.
But the app is not opened so I have to execute the shell file manually with `Show Package Contents` like below. Is this normal?
image

**Comment by hyp3rflow** [comment]
> But the app is not opened so I have to execute the shell file manually with Show Package Contents like below. Is this normal?

I found that I cannot open the original example `MyApp` on my intel Mac machine. I think this is normal.

Also, I tried examples/oak with my universal lib on intel Mac and it works well. 😊 @marc2332

**Comment by marc2332** [comment]
> @marc2332 well, I think it works fine because I can get `.dmg` file after building `example/oak` in this repo. But the app is not opened so I have to execute the shell file manually with `Show Package Contents` like below. Is this normal? image

Mmm, sorry I am not familiarized with MacOS. What is this "Show Package Contents" thing?
What is the "shell file", the app, or the installer?

**Comment by hyp3rflow** [comment]
The directory of the previous image can be shown when clicking `Show Package Contents` of MyApp (below).

image

> What is the "shell file", the app, or the installer?

Oh sorry. It is an executable file, not shell file. The `MyApp` file in the previous image (Contents/MacOS/MyApp) is that one.

**Comment by marc2332** [comment]
But, the executable file "MyApp" opens the installer, or opens the the oak app?

**Comment by hyp3rflow** [comment]
> But, the executable file "MyApp" opens the installer, or opens the the oak app?

The oak app. For clarifying, after building example, `MyApp.dmg`(installer) came out. With `MyApp.dmg`, you can install `MyApp.app`.
`MyApp.app` cannot be opened (in both intel and M1), so to open the oak app, I have to open `MyApp`(executable file) in the package contents.

**Comment by marc2332** [comment]
Okay Okay I understand now. Did you know if it was working before using the universal lib?

**Comment by marc2332** [comment]
Also, what do you mean by "cannot be opened"? Does it show any warning/error or it simply doesn't do anything? Could it be related to one of _very strict_ security measures of MacOS?

**Comment by hyp3rflow** [comment]
p{margin-top:0;margin-bottom:0}
    


    No. Same result on both lib (original and my universal lib).---- Original email ----From : Marc ***@***.***>To : ***@***.***>Cc : Yongwook ***@***.***>, ***@***.***>Date : 22.06.04 21:02 GMT +0900Subject : Re: [marc2332/deno_installer] Add m1 support (PR #1)
Okay Okay I understand now. Did you know if it was working before using the universal lib?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/marc2332/deno_installer/pull/1#issuecomment-1146596003",
"url": "https://github.com/marc2332/deno_installer/pull/1#issuecomment-1146596003",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hyp3rflow** [comment]
> Okay Okay I understand now. Did you know if it was working before using the universal lib?

Working as same, both original lib and my universal lib. I tested in my intel mac machine.

> Also, what do you mean by "cannot be opened"? Does it show any warning/error or it simply doesn't do anything? Could it be related to one of _very strict_ security measures of MacOS?

When I opened it, The icon appears very shortly on my dock (like the taskbar in windows) and closed. No warning/error comes. I guess this is because of the permission request of deno (--allow-net). When I open the executable, the permission request appears first.

**Comment by marc2332** [comment]
Can't you open the app like from the  app launcher or however is called in MacOS, instead of going to the `MyApp.app`

**Comment by hyp3rflow** [comment]
> Can't you open the app like from the app launcher or however is called in MacOS, instead of going to the `MyApp.app`

I opened it in Finder(like explorer.exe in windows), in launch control(like start menu in windows), and in the installer. The results are the same. I think this is normal.

**Comment by marc2332** [comment]
I don't think it's normal at all. In Windows it opens the app normally. Can you try maybe opening the app from a terminal (assuming MacOS puts them on PATH)?

**Comment by hyp3rflow** [comment]
> I don't think it's normal at all. 

Well, okay.

> Can you try maybe opening the app from a terminal (assuming MacOS puts them on PATH)?

I tried it with `$ open MyApp.app` in the terminal, same result.

**Comment by hyp3rflow** [comment]
Furthermore, I can get a working example of astrodon/examples/hello_world in M1 with my universal lib.
I think the problem with examples/oak is that it is just cli program, not containing any part of GUI.
image

**Comment by marc2332** [comment]
Whoah, okay, then it's just how MacOS behaves!

Thank you and sorry for all the questions :)))

**Comment by marc2332** [comment]
I will make some unit tests ASAP just to make sure all works fine and then I'll release new version

**Comment by hyp3rflow** [comment]
@marc2332 No problem! Thanks for your detailed review :)

> I will make some unit tests ASAP just to make sure all works fine and then I'll release new version

Sounds good. thanks!

**Pull request merged**
